# ==============================================================================
# Stack: <resource-group-name>
#
# The resource HCL for this RG is generated by aztfexport into THIS folder.
# Run the import from a VNet-connected host / MDP agent (the state is private):
#
#   aztfexport resource-group `
#     --backend-type azurerm `
#     --backend-config="resource_group_name=rg-netops-cicd" `
#     --backend-config="storage_account_name=<state-sa>" `
#     --backend-config="container_name=tfstate" `
#     --backend-config="key=<rg-name>.tfstate" `
#     --backend-config="use_azuread_auth=true" `
#     <rg-name>
#
# aztfexport writes the generated *.tf here and populates the remote state.
# Then refactor until `terraform plan` reports "No changes"
# (add lifecycle { ignore_changes = [...] } for Azure-injected fields, etc.).
# ==============================================================================

# --- aztfexport-generated resources go here (usually appended to this file) ---


# --- Example cross-stack reference -------------------------------------------
# Read another stack's outputs (e.g. the network stack's subnet id) instead of
# duplicating resources across stacks. Uncomment and adjust:
#
# data "terraform_remote_state" "network" {
#   backend = "azurerm"
#   config = {
#     resource_group_name  = "rg-netops-cicd"
#     storage_account_name = "REPLACE_STATE_SA"
#     container_name       = "tfstate"
#     key                  = "rg-network.tfstate"
#     use_azuread_auth     = true
#   }
# }
#
# # usage:  subnet_id = data.terraform_remote_state.network.outputs.subnet_id
